//
//  ViewController.swift
//  Static_Itea
//
//  Created by Anastasia Bilous on 2022-05-30.
//

import UIKit

class ViewController: UIViewController {
    
    func createVisitorsFromClass() -> [Visitor] {
        
        var visitors = [Visitor]()
        let numberOfVisitors = Int.random(in: 1...5)
        for item in 0..<numberOfVisitors {
            visitors.append(Visitor(name: "Name\(item+1)", dateOfVisit: item+1))
            print("name: \(visitors[item].name), data: \(visitors[item].dateOfVisit)")
        }
        return visitors
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        var randomCreatedVisitors = createVisitorsFromClass()
        // amount of visitors created as the result of random number generated inside of the function
        print("Amount of visitors generated by func: \(randomCreatedVisitors.count).")
        
        // three new instances created from Visitor outside of the function
        let visitor1 = Visitor(name: "Name10", dateOfVisit: 6)
        let visitor2 = Visitor(name: "Name11", dateOfVisit: 7)
        let visitor3 = Visitor(name: "Name12", dateOfVisit: 8)
        
        //print amount of visitors created by function plus visitors created separately ouside of function
        print("Amount of all visitors: \(Visitor.amountOfAllVisitors).")
        
        // remove one visitor from the list generated by function. In this moment deinit{} in static variable will decrease -1
        randomCreatedVisitors.remove(at: 0)
        
        print("Amount of all visitors: \(Visitor.amountOfAllVisitors).")
    }
}

